### ISSUE TITLE
fatal error: Z/hardware/CPU/architecture/6502.h: No such file or directory

### ISSUE THREAD

**Issue by usptact** [redcode/6502#6]
Installed the Z headerless library as instructed. When building this project, however, it is looking for the file `Z/hardware/CPU/architecture/6502.h`:
```
$ make config=release-dynamic all
==== Building 6502 (release-dynamic) ====
6502.c
In file included from ../sources/6502.c:47:
../API/emulation/CPU/6502.h:27:17: fatal error: Z/hardware/CPU/architecture/6502.h: No such file or directory
   27 | #       include <Z/hardware/CPU/architecture/6502.h>
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [6502.make:262: obj/release-dynamic/6502.o] Error 1
make: *** [Makefile:17: 6502] Error 2

```

The directory `architecture` and the files inside there don't exist under `CPU`:
```
$ ls /usr/local/include/Z/hardware/CPU/
6502.h  Z80.h
```

Did I miss something during Z installation?

**Comment by usptact** [comment]
It looks like I confused Z with Zeta... nvm

**Comment by redcode** [comment]
Yes, sorry. This repository contains an old version of the 6502 emulator, which still uses the old version of Zeta. Z was the old name, I have renamed the project to Zeta. I am keeping both the old and new versions as separate and distinct repos until I release a new version of the 6502 library, which is currently using the old version.

I will soon upload the new version of this 6502 emulator to the repository, including many new features, like emulation of all undocumented instructions, optimizations, CMake build system, etc. The license will also be changed from GPL to LGPL.
