### ISSUE TITLE
65C02 compatibility

### ISSUE THREAD

**Issue by fmixolydian** [redcode/6502#8]
I believe it would be nice to add compatibility for the 65C02, maybe with a compile-time flag.

**Comment by fmixolydian** [comment]
See, I'm making a 6502-based virtual computer based on this library and I started to write the BIOS, when I noticed the 65C02 instructions didn't work.

**Comment by redcode** [comment]
Version 0.2 will support 65C02 and other models. I will publish a pre-release in a few weeks.

**Comment by fmixolydian** [comment]
Nice. Thanks.
